add proxy, packageRepository and certificate injection
InseeFrLab/onyxia pull request #412
Opened 2022-11-09 04:40 UTC by alexisdondon

2022-11-10 17:05 UTC, garronej requested changes
Hey @alexisdondon,  
Sorry for the long delay.  
This PR looks good to me!  

Just apply the suggested DIFF then I'll merge and release.

2022-11-10 17:05 UTC, garronej commented on src/core/secondaryAdapters/officialOnyxiaApiClient.ts
> +                        })(),
```suggestion
                        "proxyInjection": region.proxyInjection,
                        "packageRepositoryInjection": region.packageRepositoryInjection,
                        "certificateAuthorityInjection":
                            region.certificateAuthorityInjection,
```

2022-11-14 03:59 UTC, garronej commented
Je marge dès que c'est OK. Je reste attentif

2022-11-15 09:08 UTC, alexisdondon commented
sorry i will check this today or tomorrow

2022-11-15 09:09 UTC, alexisdondon commented on src/core/secondaryAdapters/officialOnyxiaApiClient.ts
> +                        })(),
ok when scripting this i asked myself if i should take this short path or the long way

2022-11-15 09:16 UTC, alexisdondon commented
Ok i have accepted your suggestion commit

2022-11-15 09:20 UTC, alexisdondon commented
I have rerun this in local to make another check it's ok for me

2022-11-15 13:16 UTC, merged

2022-11-15 13:18 UTC, garronej commented
Thank you for your contribution.  
It's being released as I type theses words