Add support for overriding color palette
InseeFrLab/onyxia pull request #565
Opened 2023-07-28 12:13 UTC by mallport

Add functionality to override elements of the existing color palette.

The environment variable `REACT_APP_PALETTE_OVERRIDE` is written as single line JSON, corresponding to the fields in the defaultPalette in [onyxia-ui/color.ts](https://github.com/InseeFrLab/onyxia-ui/blob/main/src/lib/color.ts). The contents then patch the values in the defaultPalette.

2023-07-28 13:51 UTC, garronej requested changes
Thank you very much for your valuable contribution.

Please find my review along with some suggested modifications attached.

Looking forward to incorporating your changes!

2023-07-28 13:51 UTC, garronej commented on src/ui/theme.tsx
> +                };
In this instance, a deep merge would be the most suitable approach.

2023-07-28 13:51 UTC, garronej commented on src/ui/theme.tsx
> +                };
I believe the anticipated outcome is for the selected palette to be overwritten. For instance, an administrator may prefer the 'France' theme, yet wish to modify just a single specific color.

2023-07-28 13:51 UTC, garronej commented on .env
> +# Example: '{"focus": {"main": "#00824D","light": "#00824D","light2": "#1A9D49"}}'
```suggestion
# This parameter allows you to override some, or all, of the color palette values for the selected theme.
#
# Please adhere to the JSON format outlined in the following object:
# https://github.com/InseeFrLab/onyxia-ui/blob/0fa8667227aac328cb685cc140f3cd2186956304/src/lib/color.ts#L15-L53
#
# Should you desire to personalize the color palette without the assistance of a UI designer, 
# there is a simple way. You can copy and paste the default palette and request ChatGPT to 
# propose a variation. For instance, you might want to emphasize a specific color, like 
# "TypeScript's blue". ChatGPT can use that as a reference to generate a new color scheme 
# tailored to your preference.
#
# Example:  
#
# PALETTE_OVERRIDE: |
#   { 
#     "focus": { 
#         "main": "#00824D", 
#          "light": "#00824D"
#      } 
#   }
```

The JSON must be formatted as a single line in the .env file, but we anticipate that users will define these variables from the values.json of their Helm charts. That's why we provide examples in this particular format.

2023-07-31 08:06 UTC, mallport commented on src/ui/theme.tsx
> +                };
Thanks for your suggestions Joseph! The proposed changes are included in [55d8cc1](https://github.com/InseeFrLab/onyxia-web/pull/565/commits/55d8cc15bf343276491e9b6611f9d258ec3eb2a3) :)

2023-07-31 08:20 UTC, garronej requested changes
Hey @mmwinther,   
How are you? Thanks for the contribution!  
Here is my review.

2023-07-31 08:20 UTC, garronej commented on src/ui/theme.tsx
> +import _ from "lodash";
I'd rather avoid introducing lodash.  
Please create a util in `src/ui/tools`. It's where we put all the general utilities.

2023-07-31 08:20 UTC, garronej commented on src/ui/theme.tsx
> +function getPalette(themeId: typeof THEME_ID, paletteOverrides?: Object): PaletteBase {
Please use a cosure, we prefer avoiding creating function that are used only once.

2023-07-31 08:20 UTC, garronej commented on src/ui/theme.tsx
> +    var palette: PaletteBase;
```suggestion
    let palette: PaletteBase;
```

2023-07-31 08:20 UTC, garronej commented on src/ui/theme.tsx
> +        _.merge(palette, paletteOverrides);
This is destructive for the default palette.  
In practice it's no big deal but it's an undesired side effect.

2023-07-31 11:45 UTC, mmwinther commented
@garronej thanks for the input! We've been having a great summer here in Norway.

See the latest changes which should address your comments 👍

2023-08-01 03:56 UTC, merged

2023-08-01 04:31 UTC, garronej commented
Thanks a lot for your contribution!

2023-08-01 05:07 UTC, garronej commented
The dragoon now change color as well:  

https://github.com/InseeFrLab/onyxia-web/assets/6702424/18a11df1-986f-4722-95d8-ed2bf1fc60be

2023-08-01 06:12 UTC, garronej commented
The palette override now applies to the favicon:  

![image](https://github.com/InseeFrLab/onyxia-web/assets/6702424/114be309-f299-4494-bb85-778fa0c4fd95)

And is carried over to the login pages:  

![image](https://github.com/InseeFrLab/onyxia-web/assets/6702424/f985a8f0-3238-4a42-b0dc-75ff90214caa)

2023-08-01 06:13 UTC, garronej commented
All this is available in onyxia-web 2.23